steps:
# Steg för att installera Google Cloud SDK och distribuera Cloud Function
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
  - 'functions'
  - 'deploy'
  - 'create_bigquery_table'
  - '--runtime'
  - 'python39'
  - '--trigger-http'
  - '--entry-point'
  - 'create_bigquery_table'
  - '--region'
  - 'europe-west1'
  - '--allow-unauthenticated'
  - '--source'
  - 'create_table'  # Här pekar vi på mappen där din kod ligger
  - '--service-account'
  - 'service-accout-bigquery@tomastestproject-433206.iam.gserviceaccount.com'  # Ange din servicekonto

timeout: '600s'

# Valfria inställningar
options:
  logging: CLOUD_LOGGING_ONLY
