steps:
- name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
  entrypoint: 'gcloud'
  args:
    - 'functions'
    - 'deploy'
    - 'create_bigquery_table_2'
    - '--runtime'
    - 'python39'
    - '--trigger-http'
    - '--entry-point'
    - 'create_bigquery_table_2'
    - '--region'
    - 'europe-west1'
    - '--allow-unauthenticated'
    - '--service-account'
    - 'service-account-bigquery@tomastestproject-433206.iam.gserviceaccount.com'

timeout: '600s'

serviceAccount: 'service-account-bigquery@tomastestproject-433206.iam.gserviceaccount.com'

options:  
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  logging: CLOUD_LOGGING_ONLY
