# Använd en officiell Python-runtime som basbild
FROM python:3.9-slim

# Ställ in arbetskatalogen
WORKDIR /app

# Kopiera kravfilen och installera beroenden
COPY requirements.txt requirements.txt
RUN pip install -r requirements.txt

# Kopiera koden
COPY main.py main.py

# Definiera standardkommandot
CMD ["gunicorn", "-b", ":8080", "main:app"]
