steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-central2-docker.pkg.dev/tomastestproject-433206/app2/app2-image', '-f', 'app2/Dockerfile', 'app2']
  #Adressen kommer ifrån ditt Artifact Repo. "my-image3" är namnet på imagen.
  #'app/Dockerfile' anger vart i repot dockerfilen finns. 'app' anger från vilken mapp dockerfilen "läser" ifrån.
- name: 'gcr.io/cloud-builders/docker'        
  args: ['push', 'europe-central2-docker.pkg.dev/tomastestproject-433206/app2/app2-image']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'my-flask-app2',
         '--image', 'europe-central2-docker.pkg.dev/tomastestproject-433206/app2/app2-image',
         '--platform', 'managed',
         '--region', 'europe-central2',
         '--allow-unauthenticated']

options:
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  logging: CLOUD_LOGGING_ONLY
#Kolla upp detta så vi i framtiden sparar loggarna.