steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/tomastestproject-433206/clean-news/clean-news-img', '-f', 'transform_news/Dockerfile', 'transform_news']
  #Adressen kommer ifrån ditt Artifact Repo. "app_3-image" är namnet på imagen. 
  #'app_3/Dockerfile' anger vart i repot dockerfilen finns. 'app_3' anger från vilken mapp dockerfilen "läser" ifrån.
- name: 'gcr.io/cloud-builders/docker'        
  args: ['push', 'europe-west1-docker.pkg.dev/tomastestproject-433206/clean-news/clean-news-img']
- name: 'gcr.io/cloud-builders/gcloud'
  args: ['run', 'deploy', 'clean-news', 
          '--image', 'europe-west1-docker.pkg.dev/tomastestproject-433206/clean-news/clean-news-img',
          '--platform', 'managed',
          '--region', 'europe-west1',
          '--allow-unauthenticated',
          '--set-env-vars', 'PORT=8000'  # Ändra miljövariabeln PORT till 8000
          ]

options:  
  defaultLogsBucketBehavior: REGIONAL_USER_OWNED_BUCKET
  logging: CLOUD_LOGGING_ONLY

serviceAccount: 'service-accout-bigquery@tomastestproject-433206.iam.gserviceaccount.com'  # Replace with your actual Cloud Build service account