# Använd en officiell Python-bild som bas
FROM python:3.9-slim

# Ställ in arbetskatalogen i containern
WORKDIR /transform_news

# Kopiera requirements.txt till arbetskatalogen
COPY req.txt .

# Installera Python-biblioteken som behövs
RUN pip install --no-cache-dir -r req.txt

# Kopiera all kod till containern
COPY . .

# Exponera samma port som du sätter i PORT
EXPOSE 8000

# Starta Flask-applikationen
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "8000"]
