steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-north1-docker.pkg.dev/$tomastestproject-433206/test/my-image', '.']
- name: 'gcr.io/cloud-builders/docker'
  args: ['push','europe-north1-docker.pkg.dev/$tomastestproject-433206/test/my-image', '.']