# steps:
- name: 'gcr.io/cloud-builders/docker'
  args: ['build', '-t', 'europe-west1-docker.pkg.dev/tomastestproject-433206/fetch-news-app/fetch_news_img', '-f', 'fetch_news_app/Dockerfile', 'fetch_news_app']
