name: Lint and Test

on:
  push:
    branches:
      - mainss
  pull_request:
    branches:
      - mainss

jobs:
  lint-and-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.9'  # Specify the Python version you want to use

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install ruff pytest

    - name: Run Ruff Linting
      run: |
        # List of directories to check
        DIRS=("fetch_news" "fetch_stocks_raw" "to_ml_pipline" "transform_news_2" "transform_stocks")

        echo "Running linting with Ruff..."
        for dir in "${DIRS[@]}"; do
            ruff check "$dir"
        done

    - name: Run Pytest
      run: |
        echo "Running tests with pytest..."
        for dir in "${DIRS[@]}"; do
            pytest "$dir"
        done
